jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: hashicorp/setup-terraform@v1

    - run: terraform init

    - run: terraform lint

    - run: terraform fmt -check -diff -recursive

"on":
  push:
    branches-ignore:
    - main
    - master
